apiVersion: v1
kind: Service
metadata:
  name: esme-service-external
  namespace: esme-tp-elodie
spec:
  # Type LoadBalancer pour une exposition publique
  type: LoadBalancer 
  selector:
    # Ciblage des 3 Pods
    app: esme-app
  ports:
    - protocol: TCP
      port: 80         # Port du Service (port d'entr√©e)
      targetPort: 3000 # Port du Conteneur Node.js