apiVersion: v1
kind: Service
metadata:
  name: esme-service-internal
  namespace: esme-tp-elodie
spec:
  # Type par défaut, accessible uniquement à l'intérieur du cluster
  type: ClusterIP 
  selector:
    # Ciblage des 3 Pods créés en Tâche 2.2
    app: esme-app 
  ports:
    - protocol: TCP
      port: 80         # Port du Service (port d'entrée)
      targetPort: 3000 # Port du Conteneur Node.js